### ISSUE TITLE
babel-preset-es2015@6.13.1 breaks module-transform config

### ISSUE THREAD

**Issue by leeyeh** [rollup/rollup-plugin-babel#71]
babel-preset-es2015@6.13.1 breaks ci with: `Error: Error transforming /home/travis/build/leancloud/js-realtime-sdk/src/index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information`

revert to v6.13.0 fixed this Error.

I logged the preflight check result:

```javascript
var check = babelCore.transform( 'export default class Foo {}', options ).code;
console.log(check);
```
<details>
v6.13.1:
```javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = undefined;

var _classCallCheck2 = require("babel-runtime/helpers/classCallCheck");

var _classCallCheck3 = _interopRequireDefault(_classCallCheck2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var Foo = function Foo() {
  (0, _classCallCheck3.default)(this, Foo);
};

exports.default = Foo;
```

v6.13.0:

```javascript
import _classCallCheck from "babel-runtime/helpers/classCallCheck";

var Foo = function Foo() {
  _classCallCheck(this, Foo);
};

export { Foo as default };
```

Here is my configs:
```
{
  "presets": ["es2015-rollup"],
  "plugins": [
    "transform-runtime",
    "transform-object-rest-spread",
    "transform-decorators-legacy",
    ["transform-es2015-classes", {
      "loose": true
    }]
  ],
  runtimeHelpers: true,
}
```
</details>

**Comment by leeyeh** [comment]
It seems that babel-preset-es2015@6.13.1 changes the plugin interface, now `babel-plugin-transform-es2015-modules-commonjs` is wrapped in an array and hence it can't be removed by `babel-preset-es2015-rollup`.

<details>
babel-preset-es2015@6.13.1:
```
require('babel-preset-es2015').plugins
[ [ [Function], { loose: false } ],
  [Function],
  [Function],
  [ [Function] ],
  [Function],
  [ [Function], { loose: false } ],
  [Function],
  [Function],
  [Function],
  [ [Function], { loose: false } ],
  [ [Function], { loose: false } ],
  [Function],
  [Function],
  [Function],
  [ [Function], { loose: false } ],
  [Function],
  [ [Function], { loose: false } ],
  [Function],
  [Function],
  [ [Function], { loose: false } ],
  [ [Function], { async: false, asyncGenerators: false } ] ]
```

babel-preset-es2015@6.13.0:

```
require('babel-preset-es2015')
{ [Function]
  plugins: 
   [ [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [Function],
     [ [Function], [Object] ] ] }
```
</details>

**Comment by raphaelokon** [comment]
Revert to `babel-preset-es2015@6.13.1` fixed it for me.

**Comment by Pauan** [comment]
This looks like a duplicate of issue #72.

It's already been fixed, we're just waiting for @Rich-Harris to release a new version on npm.

**Comment by montogeek** [comment]
I just updated to 6.13.2, it has the same issue

**Comment by kobezzza** [comment]
👍

**Comment by eventualbuddha** [comment]
This should be fixed. Please either update babel-es2015-rollup or use babelrc-rollup instead.

**Comment by panzerdp** [comment]
The [rollup starter projects](https://github.com/rollup/rollup-starter-project) demonstrates how to use babelrc-rollup and solve the problem.

**Comment by yairEO** [comment]
I have every package updated and still have this error. not using **babelrc-rollup** and will not use it. I like things configured directly in my _gulpfile_ and not scattered around.

**Comment by reupen** [comment]
@yairEO I can confirm that, but `presets: [['es2015', {"modules": false}]]` works fine (note the nested arrays).

**Comment by yairEO** [comment]
@reupen - 10x! finally a straight-to-the-point solution.
why did @panzerdp had said:

> Please either update babel-es2015-rollup or...

If all was needed was to stop using `es2015-rollup` and simply use `es2015` ?
if there even a point using `babel-preset-es2015` package now?

**Comment by chengquan223** [comment]
when your main.js contain 'export'，the .babelrc should be like this，by the way，I fixed my error.
{
  "presets": [
    ["es2015", { "modules": false }]
  ]
}
